=== Ascomos21/XmlParsers/input.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://nure.ua/your_last_name/practice7"
           xmlns:tns="http://nure.ua/your_last_name/practice7">
    <xs:element name="reserve">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="gem" type="tns:gem" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="gem">
        <xs:sequence>
                    <xs:sequence>
                        <xs:element type="xs:string" name="nameGem"/>
                        <xs:element type="xs:string" name="origin"/>
                        <xs:element name="visualParameters" type="tns:visualParameters"/>
                    </xs:sequence>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="visualParameters">
        <xs:sequence>
            <xs:element name="color">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Green"/>
                        <xs:enumeration value="Yellow"/>
                        <xs:enumeration value="Blue"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="countOfFaces">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="4"/>
                        <xs:maxInclusive value="15"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Ascomos21/XmlParsers/input.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p7:reserve
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:p7="http://nure.ua/your_last_name/practice7"
        xsi:schemaLocation="http://nure.ua/your_last_name/practice7 input.xsd">
    <gem>
        <nameGem>Izumrud</nameGem>
        <origin>Mandalor</origin>
        <visualParameters>
            <color>Green</color>
            <countOfFaces>8</countOfFaces>
        </visualParameters>
    </gem>
    <gem>
        <nameGem>Zhemchug</nameGem>
        <origin>Konoha</origin>
        <visualParameters>
            <color>Yellow</color>
            <countOfFaces>8</countOfFaces>
        </visualParameters>
    </gem>
    <gem>
        <nameGem>Diamond</nameGem>
        <origin>Tatuin</origin>
        <visualParameters>
            <color>Yellow</color>
            <countOfFaces>6</countOfFaces>
        </visualParameters>
    </gem>
</p7:reserve>
